Add unsubscribe page
585-software/rocdev pull request #24
Opened 2017-10-16 20:04 UTC by dantswain

Closes #4 

Adds routes:
* `GET /unsubscribe?email=email` - Shows the unsubscribe form, fills out email field if supplied
* `DELETE /subscriptions` - Actually performs the unsubscribe

The unsubscribe is done asynchronously.  We do not retry if it fails.  This could be done later as a refinement, I think?

I considered having `GET /unsubscribe` redirect to `GET /subscriptions/unsubscribe`, but I don't know that that adds any real value.  The `/unsubscribe` url is nice and short.

2017-10-17 02:36 UTC, geowa4 requested changes
I appreciate the joke in unsubscribe.html, but I'm not sure everyone will. As for the email regex, can we make that `.+@.+`?

2017-10-17 02:36 UTC, geowa4 commented on app/lib/rocdev_web/templates/subscription/unsubscribe.html.eex
> +Whatever.  See if we care.
Uh...

2017-10-17 02:36 UTC, geowa4 commented on app/lib/rocdev_web/controllers/subscription_controller.ex
> +  @email_regex ~r/.+@.+\..+/i
I guess the owners of `http://to.` will never join this community.

2017-10-17 19:28 UTC, dantswain commented on app/lib/rocdev_web/templates/subscription/unsubscribe.html.eex
> +Whatever.  See if we care.
https://www.youtube.com/watch?v=SomQX54qhz0

2017-10-19 14:15 UTC, geowa4 approved these changes

2017-10-19 14:15 UTC, merged