Create a feature request issue template
585-software/rocdev pull request #37
Opened 2017-10-25 15:26 UTC by kylemacey

Creates an issue template for requesting features. Will be accessible at https://github.com/585-software/rocdev/issues/new?template=feature.md once merged. 

Closes #27 

cc:\ @geowa4 

### TODO

- [ ] Link from README.md or CONTRIBUTING.md (looking for feedback here)

2017-10-26 00:29 UTC, geowa4 requested changes
You're showing me some omissions in my CONTRIBUTING.md.  I'm making a bug for that.

2017-10-26 00:29 UTC, geowa4 commented on .github/ISSUE_TEMPLATE/feature.md
> +Describe in full detail the behavior that you would like implemented. Use screenshots or mock-ups if applicable.
Can you put each sentence on its own line? It makes it easier to rearrange and delete them while also making diffs easier to read.

2017-10-26 00:29 UTC, geowa4 commented on .github/ISSUE_TEMPLATE/feature.md
> +### Feature description
Can you capitalize the major words in headings?

2017-10-26 00:32 UTC, geowa4 commented
Regarding where to link to this, I think it would be best as a sibling to [Getting Started](https://github.com/585-software/rocdev#getting-started) in README.md.

2017-10-26 15:58 UTC, kylemacey commented
@geowa4 Updated!

2017-10-27 00:43 UTC, geowa4 approved these changes

2017-10-27 00:46 UTC, geowa4 commented
Thanks, @kylemacey. I'm working on #9 now. Once I'm done with that I was going to do #38, but I just realized that's another issue you or someone else could do to get a Hacktoberfest shirt.

2017-10-27 00:46 UTC, merged